services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: auth
    volumes:
      - auth_pg_data:/bitnami/postgresql

volumes:
  auth_pg_data:
